# Generated by Django 3.1.5 on 2021-02-11 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=200, null=True)),
                ('Area', models.CharField(max_length=200, null=True)),
                ('Pan_Number', models.CharField(max_length=20, null=True)),
                ('Bank_Account', models.CharField(max_length=20, null=True)),
                ('IFSC_code', models.CharField(max_length=20, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
