# Generated by Django 3.1.5 on 2021-02-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_operator_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='is_staff',
            field=models.BooleanField(default=1),
        ),
    ]
