# Generated by Django 3.1.5 on 2021-02-11 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_operator_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='Address',
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_Number', models.CharField(max_length=20, null=True)),
                ('STB_Number', models.CharField(max_length=20, null=True)),
                ('Area_Name', models.CharField(max_length=100, null=True)),
                ('NODE_Number', models.CharField(max_length=20, null=True)),
                ('Bank_Account', models.CharField(max_length=20, null=True)),
                ('IFSC_code', models.CharField(max_length=20, null=True)),
                ('is_active', models.BooleanField(default=1)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
