# Generated by Django 3.1.5 on 2021-02-12 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210212_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operator',
            old_name='is_operator',
            new_name='is_staff',
        ),
    ]
