# Generated by Django 3.1.5 on 2021-02-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210212_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='createPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Plan_ID', models.CharField(max_length=50, null=True)),
                ('validity', models.CharField(max_length=50, null=True)),
                ('price', models.CharField(max_length=50, null=True)),
                ('company_name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=50, null=True)),
                ('speed', models.CharField(max_length=50, null=True)),
                ('data_limit', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
