# Generated by Django 3.1.5 on 2021-02-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_createplans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SR_No', models.CharField(max_length=50, null=True, unique=True, verbose_name='Serial Number')),
                ('Name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('Emp_Number', models.CharField(max_length=10, null=True, verbose_name='Employee Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('department', models.CharField(max_length=100, null=True, verbose_name='Department')),
                ('DOJ', models.DateField(verbose_name='Date of Joining')),
            ],
        ),
    ]
