# Generated by Django 3.1.5 on 2021-02-18 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0015_auto_20210216_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='STB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, null=True, verbose_name='Serial Number')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('DOP', models.DateField(verbose_name='Date Of Purchase')),
                ('Type', models.CharField(choices=[('1', 'Prepaid'), ('2', 'Postpaid'), ('3', 'Complementary')], default='1', max_length=50, null=True, verbose_name='Type')),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default='1', max_length=50, verbose_name='Status')),
                ('box_type', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default='1', max_length=50, verbose_name='Box Type')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remark')),
                ('model_number', models.CharField(max_length=50, null=True, verbose_name='Model Number')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, null=True, verbose_name='Serial Number')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('DOP', models.DateField(verbose_name='Date Of Purchase')),
                ('STB_count', models.IntegerField(verbose_name='STB Count')),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default='1', max_length=50, verbose_name='Status')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remark')),
                ('model_number', models.CharField(max_length=50, null=True, verbose_name='Model Number')),
                ('operator_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.operator', verbose_name='Operator Name')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='NODE_Number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.node'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='STB_Number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.stb'),
        ),
    ]
