# Generated by Django 3.1.5 on 2021-02-18 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210218_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='operator_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.operator', verbose_name='Operator Name'),
        ),
    ]
