# Generated by Django 3.1.5 on 2021-02-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210218_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='stb',
            name='is_assigned',
            field=models.BooleanField(default=False, verbose_name='Assigned'),
        ),
        migrations.AddField(
            model_name='stb',
            name='user_id',
            field=models.CharField(max_length=50, null=True, verbose_name='User ID'),
        ),
    ]
