# Generated by Django 3.1.5 on 2021-02-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('profile_id', models.CharField(max_length=50, null=True, verbose_name='Profile ID')),
            ],
        ),
    ]
