# Generated by Django 3.1.5 on 2021-02-18 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20210219_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='active',
            new_name='act',
        ),
    ]
