# Generated by Django 3.1.5 on 2021-02-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_profile_act'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='act',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
