# Generated by Django 3.1.5 on 2021-02-19 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20210219_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=50, verbose_name='')),
                ('name', models.CharField(max_length=50, verbose_name='')),
                ('mobile', models.CharField(max_length=50, verbose_name='')),
                ('email', models.CharField(max_length=50, verbose_name='')),
                ('address', models.CharField(max_length=50, verbose_name='')),
                ('message_box', models.TextField(verbose_name='Message')),
                ('sr_type', models.CharField(max_length=50, verbose_name='')),
                ('sub_type', models.CharField(max_length=50, verbose_name='')),
                ('status', models.CharField(choices=[('1', 'Open'), ('2', 'Work in Progress'), ('3', 'Complete'), ('4', 'Closed'), ('5', 'Canceled')], default='1', max_length=50, verbose_name='')),
                ('allotment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.employee', verbose_name='Allotment')),
                ('node_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.node', verbose_name='Node Details')),
            ],
        ),
    ]
