# Generated by Django 3.1.5 on 2021-02-19 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_servicerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='allotment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.employee'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='node_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.node'),
        ),
    ]
