# Generated by Django 3.1.5 on 2021-02-19 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20210219_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='address',
            field=models.CharField(max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='allotment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.employee'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='message_box',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='mobile',
            field=models.CharField(max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='node_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.node'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_id',
            field=models.CharField(max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='sr_type',
            field=models.CharField(max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='sub_type',
            field=models.CharField(max_length=50, null=True, verbose_name=''),
        ),
    ]
