# Generated by Django 3.1.5 on 2021-02-19 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20210219_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='node_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.node'),
        ),
    ]
