# Generated by Django 3.1.5 on 2021-02-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20210219_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='message_box',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Message'),
        ),
    ]
