# Generated by Django 3.1.5 on 2021-02-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20210219_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Work in Progress', 'Work in Progress'), ('Complete', 'Complete'), ('Closed', 'Closed'), ('Canceled', 'Canceled')], default='Open', max_length=50, verbose_name='Status'),
        ),
    ]
