# Generated by Django 3.1.5 on 2021-02-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_remove_employee_sr_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='SR_No',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Serial Number'),
        ),
    ]
