# Generated by Django 3.1.5 on 2021-02-20 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_employee_sr_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='allotment',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
