# Generated by Django 3.1.5 on 2021-02-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_employee_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stb',
            name='box_type',
            field=models.CharField(choices=[('1', 'SD'), ('2', 'HD'), ('3', 'HD+'), ('4', 'Other')], default='1', max_length=50, verbose_name='Box Type'),
        ),
    ]
