# Generated by Django 3.1.5 on 2021-02-22 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20210222_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='operator_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.operator', verbose_name='Operator Name'),
        ),
    ]
