# Generated by Django 3.1.5 on 2021-02-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20210222_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='area',
            field=models.CharField(max_length=50, null=True, verbose_name='Model Number'),
        ),
    ]
