# Generated by Django 3.1.5 on 2021-02-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_router'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, verbose_name='IP Address'),
        ),
    ]
