# Generated by Django 3.1.5 on 2021-02-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_auto_20210222_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_account_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Bank Account Number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='branch_addresss',
            field=models.CharField(max_length=50, null=True, verbose_name='Branch Address'),
        ),
        migrations.AddField(
            model_name='employee',
            name='branch_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Branch Name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='employee',
            name='company_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ifsc_code',
            field=models.CharField(max_length=50, null=True, verbose_name='IFSC COde'),
        ),
        migrations.AddField(
            model_name='employee',
            name='permission',
            field=models.CharField(max_length=50, null=True, verbose_name='Permission'),
        ),
        migrations.AddField(
            model_name='employee',
            name='pincode',
            field=models.CharField(max_length=50, null=True, verbose_name='Pincode'),
        ),
    ]
