# Generated by Django 3.1.5 on 2021-02-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20210222_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createplans',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='createplans',
            old_name='Plan_ID',
            new_name='plan_ID',
        ),
    ]
