# Generated by Django 3.1.5 on 2021-02-22 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_auto_20210222_1920'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='createPlans',
            new_name='Plans',
        ),
    ]
