# Generated by Django 3.1.5 on 2021-02-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_auto_20210222_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stb',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='User ID'),
        ),
    ]
