# Generated by Django 3.1.5 on 2021-02-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_auto_20210222_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50, null=True, verbose_name='Make')),
                ('qty', models.IntegerField(null=True, verbose_name='Quantity')),
                ('amount', models.IntegerField(null=True, verbose_name='Amount ₹')),
                ('bill_number', models.IntegerField(verbose_name='Bill Number')),
                ('date_of_purchase', models.DateField(verbose_name='Date Of Purchase')),
                ('vendor_name', models.CharField(max_length=50, null=True, verbose_name='Make')),
                ('warehouse', models.CharField(choices=[('0', '-----'), ('1', 'Beed'), ('2', 'Akola')], default='0', max_length=50, verbose_name='Warehouse')),
                ('receiver_name', models.CharField(max_length=50, null=True, verbose_name='Make')),
            ],
        ),
        migrations.AlterField(
            model_name='node',
            name='status',
            field=models.CharField(choices=[('0', '-----'), ('1', 'Active'), ('2', 'Inactive')], default='1', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='router',
            name='router_type',
            field=models.CharField(choices=[('0', '-----'), ('1', 'Data'), ('2', 'Wifi'), ('3', 'Dual Band')], default='0', max_length=50, verbose_name='Router Type'),
        ),
        migrations.AlterField(
            model_name='router',
            name='status',
            field=models.CharField(choices=[('0', '-----'), ('1', 'Active'), ('2', 'Inactive')], default='0', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='router',
            name='type1',
            field=models.CharField(choices=[('0', '-----'), ('1', 'Prepaid'), ('2', 'Postpaid'), ('3', 'Complementary')], default='0', max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('0', '-----'), ('1', 'Open'), ('2', 'Work in Progress'), ('3', 'Complete'), ('4', 'Closed'), ('5', 'Canceled')], default='0', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='stb',
            name='Type',
            field=models.CharField(choices=[('0', '-----'), ('1', 'Prepaid'), ('2', 'Postpaid'), ('3', 'Complementary')], default='0', max_length=50, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='stb',
            name='box_type',
            field=models.CharField(choices=[('0', '-----'), ('1', 'SD'), ('2', 'HD'), ('3', 'HD+'), ('4', 'Other')], default='0', max_length=50, verbose_name='Box Type'),
        ),
        migrations.AlterField(
            model_name='stb',
            name='status',
            field=models.CharField(choices=[('0', '-----'), ('1', 'Active'), ('2', 'Inactive')], default='0', max_length=50, verbose_name='Status'),
        ),
    ]
