# Generated by Django 3.1.5 on 2021-02-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_auto_20210223_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stb',
            name='Type',
            field=models.CharField(choices=[('---', '-----'), ('Prepaid', 'Prepaid'), ('Postpaid', 'Postpaid'), ('Complementary', 'Complementary')], default='---', max_length=50, null=True, verbose_name='Type'),
        ),
    ]
