# Generated by Django 3.1.5 on 2021-02-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_auto_20210226_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stb',
            name='Type',
            field=models.CharField(choices=[('0', '-----'), ('1', 'Prepaid'), ('2', 'Postpaid'), ('3', 'Complementary')], default='0', max_length=50, null=True, verbose_name='Type'),
        ),
    ]
