# Generated by Django 3.1.5 on 2021-02-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='NODE_Number',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='STB_Number',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='account_no',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_account',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
