# Generated by Django 3.1.5 on 2021-02-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210211_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='NODE_Number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='STB_Number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_account',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
